### PR TITLE
Update plugin for 2023.1

### PR DESCRIPTION
**Pull request by haocheng**
- Update intellij plugin to latest version
- Update dependencies for 2023.1
- Changelog

### CODE REVIEW

**Comment by haocheng** [comment]
If anyone wants to use Intellij IDEA 2023.1 now, I have built a new version of the plugin to support it:
[thrift-2023.1.zip](https://github.com/arhont375/intellij-thrift/files/11109908/thrift-2023.1.zip)

**Comment by mkasberg** [comment]
Thanks a bunch!

@arhont375 Would love to see this update get pushed to [your plugin](https://plugins.jetbrains.com/plugin/19912-thrift-support-fork-).

**Comment by arhont375** [comment]
Oh, sorry for the delay. Let me do that

**Comment by arhont375** [comment]
Realized I had notifications disabled for this repo, oops, so next time reaction time should be smaller.

Plugin now under JB review

**Pull request merged**
